# version: 0.1.0
# surat jalan

apps:
  app1:
    platform: wordpress
    storage:
      - wp-content
      - backup
    deploy:
      - apt-get update && apt-get upgrade -y && apt-get install -y mariadb-client php-mbstring
  app2:
    platform: custom
    type: php

dbs:
  db1:
    engine: mysql
