# version: 0.1.0
# surat jalan

domain: artworkz.co.id

apps:
  app1:
    platform: wordpress
    storage:
      - wp-content
      - backup
    deploy:
      - apt-get update && apt-get upgrade -y && apt-get install -y mariadb-client php-mbstring

dbs:
  db1:
    engine: mysql
