sudo: required
language: python
services:
- docker
- mysql
script:
- sudo apt-get update
- sudo apt-get install -y nginx-full mysql-client
- dpkg-deb --build arnpod-0.1.0
- dpkg -i arnpod-0.1.0.deb
- bash -x /usr/sbin/petugas
