sudo: required
language: python
services:
  - docker

before_install:
  - docker pull mariadb:5.5
  - docker run -d -p 127.0.0.1:3307:3306 --name mysqld -e MYSQL_ROOT_PASSWORD=root mariadb:5.5
  - sleep 30

script:
  - export APDEBUG=1
  - export MARGONO_DEBUG=1
  - sudo apt-get update
  - sudo apt-get install -y nginx-full mysql-client-5.5 gawk
  - dpkg-deb --build arnpod-0.1.0
  - sudo dpkg -i arnpod-0.1.0.deb
  - cat ~/.my.cnf
  - sudo mkdir -p /usr/local/lib/arnpod/share/artefact
  - sudo margono r .suratjalan.yml
