sudo: required
language: python
services:
- docker
- mysql
script:
- sudo apt-get update
- sudo apt-get install -y nginx-full mysql-client-5.5
- dpkg-deb --build arnpod-0.1.0
- sudo dpkg -i arnpod-0.1.0.deb
- sudo bash -x /usr/sbin/petugas
